sailfishos/sailfish-secrets

rpm/sailfish-secrets.spec
Signed-off-by: Aleksey Mikhaylov <a.mikhaylov@omprussia.ru>
=> Add QtTest to build requires for test packages

api/libsailfishcrypto/libsailfishcrypto.pri, api/libsailfishsecrets/libsailfishsecrets.pri, tests/tst_crypto/tst_crypto.pro
Signed-off-by: Aleksey Mikhaylov <a.mikhaylov@omprussia.ru>
=> Fix out of source build

daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/daemon.pro, daemon/plugin_p.h
It helps to find the root cause of a plugin not loading, like missing symbols…
=> Add an error message when plugin cannot be loaded.

lib/Crypto/Crypto.pro, lib/Secrets/Secrets.pro, rpm/sailfish-secrets.spec
Also improve the post and postun to avoid unrecoverable failure
during image creation where ldconfig is not available.
=> Fix pkgconfig generation

lib/Crypto/keypairgenerationparameters.cpp, plugins/opensslcryptoplugin/evp/evp.c, plugins/opensslcryptoplugin/evp/evp_helpers_p.h, plugins/opensslcryptoplugin/evp/evp_p.h, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp, plugins/opensslcryptoplugin/opensslcryptoplugin.h, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp
Implements EC key generation and adds new digest functions.
=> EC key generation, new digest functions, RSA encryption

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/crypto_p.h, daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/CryptoImpl/cryptorequestprocessor_p.h, lib/Crypto/Crypto.pro, lib/Crypto/cryptomanager.cpp, lib/Crypto/cryptomanager.h, lib/Crypto/cryptomanager_p.h, lib/Crypto/extensionplugins.h, lib/Crypto/importkeyrequest.cpp, lib/Crypto/importkeyrequest.h, lib/Crypto/importkeyrequest_p.h, lib/Crypto/importstoredkeyrequest.cpp, lib/Crypto/importstoredkeyrequest.h, lib/Crypto/importstoredkeyrequest_p.h, lib/Crypto/result.h, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp, plugins/opensslcryptoplugin/opensslcryptoplugin.h, plugins/sqlcipherplugin/cryptoplugin.cpp, plugins/sqlcipherplugin/sqlcipherplugin.h, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp
These will validate a key and if a passphrase is required
prompt the user to enter it, then either return the key
without a passphrase for securely store it depending
on the request.
=> Add ImportKey and ImportStoredKey requests.

README.md, sailfish-secrets.pro
I added some further info and thoughts to the readme. Is there anything else that would be useful to mention here?
=> Improve readme.

daemon/SecretsImpl/secretsrequestprocessor.cpp
If a collection is created by a privileged application with its
authentication plugin set to the in-app authentication plugin
(e.g. for in-process flows in Settings application), we don't want
non-privileged third-party applications to be able to use in-app
authentication to unlock the collection (as that would leak the
unlock code to the third-party application).
This commit ensures that we always use the appropriate (system default)
authentication plugin for non-privileged applications, if they do
not own the collection (or standalone secret) in question.
=> [sailfish-secrets] Use appropriate auth plugin depending on permissions. Contributes to JB#36797

plugins/opensslcryptoplugin/evp/evp.cpp, plugins/opensslcryptoplugin/evp/evp_helpers_p.h, plugins/opensslcryptoplugin/evp/evp_p.h, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp
This PR is a small refactor of the signing and verification code that removes code duplication and ensures that the same code path is used for both cipher sessions and normal operations, thus reducing the chance of regressions.
=> Refactor signing and verify

daemon/SecretsImpl/secretsrequestprocessor.cpp, qml/Secrets/main.cpp, qml/Secrets/plugintypes.h
This contains also another commit that adjusts master unlocking error code.
=> Expose lock code request

daemon/SecretsImpl/SecretsImpl.pri, daemon/SecretsImpl/dataprotector.cpp, daemon/SecretsImpl/dataprotector_p.h, daemon/SecretsImpl/metadatadb.cpp, daemon/SecretsImpl/secrets.cpp, rpm/sailfish-secrets.spec, tests/Secrets/Secrets.pro, tests/Secrets/tst_dataprotection/tst_dataprotection.cpp, tests/Secrets/tst_dataprotection/tst_dataprotection.h, tests/Secrets/tst_dataprotection/tst_dataprotection.pro
Do not merge yet, this is incomplete. Only submitting to get early feedback for the code.
=> Data protection for sensitive files

lib/Crypto/cryptodaemonconnection.cpp, lib/Secrets/secretsdaemonconnection.cpp, tools/secrets-tool/commandhelper.cpp, tools/secrets-tool/main.cpp
This allows testing InteractionRequest flows via the secrets-tool.
=> [sailfish-secrets] Add option to tool to request user input. Contributes to JB#42034

lib/Secrets/request.h, qml/Secrets/Secrets.pro, qml/Secrets/findsecretsrequestwrapper.cpp, qml/Secrets/findsecretsrequestwrapper.h, qml/Secrets/main.cpp, qml/Secrets/plugintypes.h
Adapt the code from StoredKeyIdentifiersRequest from Crypto to be able to list secret identifiers with FindSecretsRequest.
=> Adjust various things to be able to use FindSecretsRequest from QML

.gitignore, daemon/sailfish-secretsd.service, lib/Crypto/Plugins/extensionplugins.cpp, lib/Crypto/Plugins/extensionplugins.h, lib/Secrets/Plugins/extensionplugins.cpp, lib/Secrets/Plugins/extensionplugins.h, plugins/gnupgplugin/gnupgplugin.pro, plugins/gnupgplugin/gpgme_p.h, plugins/gnupgplugin/gpgmebase.cpp, plugins/gnupgplugin/gpgmebase.h, plugins/gnupgplugin/gpgmestorage.cpp, plugins/gnupgplugin/gpgmestorage.h, plugins/gnupgplugin/openpgpplugin/openpgpplugin.pro, plugins/gnupgplugin/openpgpplugin/plugin.cpp, plugins/gnupgplugin/openpgpplugin/plugin.h, plugins/gnupgplugin/pinentry/pinentry.cpp, plugins/gnupgplugin/pinentry/pinentry.pro, plugins/gnupgplugin/pinentry/qassuanserver.cpp, plugins/gnupgplugin/pinentry/qassuanserver.h, plugins/gnupgplugin/smimeplugin/plugin.cpp, plugins/gnupgplugin/smimeplugin/plugin.h, plugins/gnupgplugin/smimeplugin/smimeplugin.pro, plugins/plugins.pro, rpm/sailfish-secrets.spec, tests/plugins/plugins.pro, tests/plugins/testgnupgplugin/testgnupgplugin.pro, tests/plugins/testgnupgplugin/tst_gnupgplugin.cpp, tests/plugins/testopenpgpplugin/testopenpgpplugin.pro
Hello @Venemo, @chriadam and @jpetrell. This is a pull request to show the current state of affair on the GnuPG plugin. It's not ready yet and I'm still working on it. It currently contains basics to generate a key and sign with it (not fully working yet though). Later on I'll add the code to create a pinentry as discussed in #5.
It can serve as base for the discussion of tomorrow's meeting though if you are still fit after the sprint of recent days ;)
Congrats for the work by the way.
=> Implement a gpgme-based crypto plugin allowing to use PGP keys

lib/Crypto/cryptomanager.cpp, lib/Crypto/cryptomanager.h, tests/Crypto/cryptotest.cpp, tests/Crypto/cryptotest.h, tests/Crypto/tst_crypto/tst_crypto.cpp, tests/Crypto/tst_crypto/tst_crypto.pro, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp, tests/Crypto/tst_cryptorequests/tst_cryptorequests.pro, tests/Crypto/tst_cryptosecrets/tst_cryptosecrets.cpp, tests/Crypto/tst_cryptosecrets/tst_cryptosecrets.pro
…nfigurable. Contributes to JB#40058
- Extract some common test code into CryptoTest
- Make the unit test plugins configurable via environment variables
=> [sailfish-crypto] Rework Crypto unit tests. Contributes to JB#40058

daemon/SecretsImpl/applicationpermissions_p.h, daemon/daemon.pro, rpm/sailfish-secrets.spec
- Prompt text now is more clear and brief
- Prompt text template is changed for platform applications
=> [daemon] Modify prompt text for user input. Contributes to JB#45838

3rdparty/qt5-sqlcipher/qt5-sqlcipher.pro, daemon/daemon.pro, daemon/main.cpp, examples/plugins/examplecryptoplugin/examplecryptoplugin.pro, examples/plugins/examplecryptostorageplugin/examplecryptostorageplugin.pro, lib/SecretsCrypto/SecretsCrypto.pro, plugins/exampleusbtokenplugin/exampleusbtokenplugin.pro, plugins/gnupgplugin/openpgpplugin/openpgpplugin.pro, plugins/gnupgplugin/smimeplugin/smimeplugin.pro, plugins/inappauthplugin/inappauthplugin.pro, plugins/opensslcryptoplugin/opensslcryptoplugin.pro, plugins/opensslplugin/opensslplugin.pro, plugins/passwordagentauthplugin/passwordagentauthplugin.pro, plugins/sqlcipherplugin/sqlcipherplugin.pro, plugins/sqliteplugin/sqliteplugin.pro, qml/Crypto/Crypto.pro, qml/Secrets/Secrets.pro, rpm/sailfish-secrets.spec, tests/clients/authentication/authentication.pro, tests/clients/authentication/main.cpp, tests/plugins/testexampleusbtokenplugin/testexampleusbtokenplugin.pro, tests/plugins/testinappauthplugin/testinappauthplugin.pro, tests/plugins/testopenpgpplugin/testopenpgpplugin.pro, tests/plugins/testopensslcryptoplugin/testopensslcryptoplugin.pro, tests/plugins/testopensslplugin/testopensslplugin.pro, tests/plugins/testpasswordagentauthplugin/testpasswordagentauthplugin.pro, tests/plugins/testsqlcipherplugin/testsqlcipherplugin.pro, tests/plugins/testsqliteplugin/testsqliteplugin.pro
=> [aarch64] Use macros. Do not hardcode lib dir. Contributes to JB#50028

lib/Crypto/doc/doc.pro, lib/Secrets/doc/doc.pro, rpm/sailfish-secrets.spec
Got rid of some excessive redundancy in the .spec too.
@vigejolla @rainemak
=> [secrets] Adapt to sailfish-qdoc-template. JB#54004

daemon/SecretsImpl/secrets.cpp
- Set summary/body instead of previewSummary/previewBody.
- Add displayName to actions.
=> [SecretsCrypto] Update notification configuration. JB#50448

examples/apps/apps.pro, examples/apps/qmlexample/README, examples/apps/qmlexample/main.cpp, examples/apps/qmlexample/main.qml, examples/apps/qmlexample/qmlexample.pro, examples/apps/qmlexample/resources.qrc, qml/Crypto/main.cpp, qml/Crypto/plugintypes.h, qml/Secrets/main.cpp, qml/Secrets/plugintypes.h, rpm/sailfish-secrets.spec, tests/qml/qml.pro, tests/qml/tst_qml_rsaencryptdecrypt/tst_qml_rsaencryptdecrypt.cpp, tests/qml/tst_qml_rsaencryptdecrypt/tst_qml_rsaencryptdecrypt.pro, tests/qml/tst_qml_rsaencryptdecrypt/tst_qml_rsaencryptdecrypt.qml, tests/qml/tst_qml_signing/tst_qml_signing.qml
Note: the QML API is still experimental and subject to change.
=> Add a QML example
