sailfishos/sailfish-secrets

plugins/sqlcipherplugin/sqlcipherplugin.cpp, rpm/sailfish-secrets.spec
Previously, the sqlcipher plugin used the incorrect path to store
its database files in depending on whether it was constructed in
test mode or not.  This commit fixes that.
It also fixes packaging to ensure the Qt5Sql SQLCipher driver plugin
is installed.
=> Fix typo in sqlcipher plugin

daemon/main.cpp, doc/index.qdoc, doc/sailfish.cpp, lib/Crypto/Crypto.pro, lib/Crypto/doc/doc.pro, lib/Crypto/doc/sailfish-crypto-overview.qdoc, lib/Crypto/doc/sailfish-crypto-plugins.qdoc, lib/Crypto/doc/sailfish-crypto.cpp, lib/Crypto/doc/sailfish-crypto.qdocconf, lib/Secrets/Secrets.pro, lib/Secrets/doc/doc.pro, lib/Secrets/doc/sailfish-secrets-overview.qdoc, lib/Secrets/doc/sailfish-secrets-plugins.qdoc, lib/Secrets/doc/sailfish-secrets.cpp, lib/Secrets/doc/sailfish-secrets.qdocconf, lib/SecretsCrypto/README, lib/lib.pro, plugins/inappauthplugin/inappauthplugin.pro, plugins/opensslcryptoplugin/opensslcryptoplugin.pro, plugins/opensslplugin/opensslplugin.pro, plugins/sqlcipherplugin/sqlcipherplugin.pro, plugins/sqliteplugin/sqliteplugin.pro, rpm/sailfish-secrets.spec, tests/plugins/testinappauthplugin/testinappauthplugin.pro, tests/plugins/testopensslcryptoplugin/testopensslcryptoplugin.pro, tests/plugins/testopensslplugin/testopensslplugin.pro, tests/plugins/testsqlcipherplugin/testsqlcipherplugin.pro, tests/plugins/testsqliteplugin/testsqliteplugin.pro
This commit adds documentation for the Sailfish OS Secrets and Crypto
Framework, including overview documentation for the Sailfish OS Secrets
Library and the Sailfish OS Crypto Library.
It also changes the install path of C++ plugins and devel headers
for symmetry with the install path for QML plugins and documentation.
=> [sailfish-secrets] Add framework overview documentation. Contributes to JB#36797

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/crypto_p.h, daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/CryptoImpl/cryptorequestprocessor_p.h, lib/Crypto/cryptodaemonconnection.cpp, lib/Crypto/cryptomanager.cpp, lib/Crypto/cryptomanager_p.h, lib/Crypto/extensionplugins.h, lib/Crypto/key.h, lib/Crypto/serialisation.cpp, lib/Crypto/serialisation_p.h, lib/Crypto/storedkeyrequest.cpp, lib/Crypto/storedkeyrequest.h, lib/Crypto/storedkeyrequest_p.h, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp, plugins/opensslcryptoplugin/opensslcryptoplugin.h, plugins/sqlcipherplugin/cryptoplugin.cpp, plugins/sqlcipherplugin/sqlcipherplugin.h, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp, tests/Crypto/tst_cryptosecrets/tst_cryptosecrets.cpp
Previously, the StoredKeyRequest would retrieve all of the data
associated with a key entry, including metadata, public key data, and
private key data.  This commit allows the client to specify which
of these portions of data they wish to retrieve.
This allows, for example, the client to retrieve just the public
key data portion, allowing the client to limit potential secret
key data leakage in the case where they suspect that the secrecy
of their process's memory address space may be compromised.
Contributes to JB#40058
=> [sailfish-crypto] Allow the client to limit retrieve key data. Contributes to JB#40058

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/crypto_p.h, daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/CryptoImpl/cryptorequestprocessor_p.h, lib/Crypto/cryptomanager.cpp, lib/Crypto/cryptomanager_p.h, lib/Crypto/decryptrequest.cpp, lib/Crypto/decryptrequest.h, lib/Crypto/decryptrequest_p.h, lib/Crypto/encryptrequest.cpp, lib/Crypto/encryptrequest.h, lib/Crypto/encryptrequest_p.h, lib/Crypto/extensionplugins.h, plugins/opensslcryptoplugin/cryptoplugin_common.cpp, plugins/opensslcryptoplugin/opensslcryptoplugin.h, plugins/sqlcipherplugin/sqlcipherplugin.h, tests/Crypto/tst_crypto/tst_crypto.cpp, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp, tests/Crypto/tst_cryptosecrets/tst_cryptosecrets.cpp
Add support for user-supplied initialisation vector data, and remove
the unnecessary digest parameter.
Contributes to JB#40058
=> [sailfish-crypto] Improve the encrypt/decrypt client API. Contributes to JB#40058

lib/Crypto/cryptomanager.h, lib/Crypto/result.h, plugins/opensslcryptoplugin/evp/evp.c, plugins/opensslcryptoplugin/evp/evp_helpers_p.h, plugins/opensslcryptoplugin/evp/evp_p.h, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp, rpm/sailfish-secrets.spec, tests/Crypto/Crypto.pro, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp, tests/Crypto/tst_evp/tst_evp.cpp, tests/Crypto/tst_evp/tst_evp.h, tests/Crypto/tst_evp/tst_evp.pro
Adds support for:
* Signing with RSA private key
* Verifying a signature with an RSA public key
* Calculating a digest
Tests:
* end-to-end tests in `tst_cryptorequests` for signing, verify and digest
* openssl command line tests to ensure that our EVP code is sane
Current limitations:
* only supports `PaddingNone`
* no support for MAC (message authentication codes)
I believe this is now ready to be merged.
=> Sign, verify and digest support for OpenSSL crypto plugin

plugins/opensslcryptoplugin/evp/evp.c, plugins/opensslcryptoplugin/opensslcryptoplugin.cpp, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp
WIP. The test fails at the moment because the decrypted plaintext has an extra 16 bytes on the end. Looking at the plugin, it looks like GCM decryption is implemented correctly as per the openssl docs, so this needs some investigation as to why it's failing.
=> [sailfish-crypto] Add autotests for GCM mode (for AES encryption). Contributes to JB#40058

rpm/sailfish-secrets.spec
Well, title says all: some build packages were missing.
=> [sailfish-secrets] Add missing dependencies for QML tests.

rpm/sailfish-secrets.spec, tests/qml/tst_qml_signing/tst_qml_signing.pro
Have Qt5QuickTest build requirement in each test package.
=> [sailfish-secrets] Add missing Qt5QuickTest dependencies and cleanup extras. Contributes to JB#36797

daemon/SecretsImpl/SecretsImpl.pri, plugins/opensslplugin/opensslplugin.pro, plugins/sqlcipherplugin/sqlcipherplugin.pro
Now sailfish-secrets can be started without test packages being installed as service.
=> [sailfish-secrets] Fix libcrypto linking to sqlcipherplugin and opensslplugin. Contributes to JB#41547

plugins/sqlcipherplugin/encryptedstorageplugin.cpp
Collection database file detection was failing due to full path not
being provided in the QFile::exists() check.
=> Fix bug in SQLCipher plugin

rpm/sailfish-secrets.spec, sailfish-secrets.pro, tools/secrets-tool/commandhelper.cpp, tools/secrets-tool/commandhelper.h, tools/secrets-tool/main.cpp, tools/secrets-tool/manual-test.sh, tools/secrets-tool/secrets-tool.pro, tools/tools.pro
This commit adds a command line tool which allows the user to perform
a variety of operations via the Secrets and Crypto APIs.
It can be used to manually test the various authentication and user
input flows, to manually verify that a particular plugin is working
as expected, or to perform useful operations (such as signing,
verification, encryption or decryption) via a particular plugin.
Contributes to JB#36797 and JB#40058
=> [sailfish-secrets] Write command line tool. Contributes to JB#36797

daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/SecretsImpl/pluginwrapper.cpp, daemon/SecretsImpl/pluginwrapper_p.h, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretscryptohelpers.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, daemon/controller.cpp, daemon/controller_p.h, lib/SecretsPluginApi/extensionplugins.cpp, lib/SecretsPluginApi/extensionplugins.h, plugins/exampleusbtokenplugin/exampleusbtokenplugin.h, plugins/inappauthplugin/plugin.h, plugins/opensslcryptoplugin/opensslcryptoplugin.h, plugins/opensslplugin/plugin.h, plugins/passwordagentauthplugin/passwordagentplugin.h, plugins/sqlcipherplugin/sqlcipherplugin.h, plugins/sqliteplugin/plugin.h
Note that the display name should be informative and human-readable,
however we do not enforce uniqueness (in order to avoid plugin
ordering issues resulting in lost-data issues).
Plugin implementors should take care to ensure that the display name
reported by their plugin is useful and not confusing.
=> [sailfish-secrets] Add displayName() to PluginBase API. Contributes to JB#36797

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/crypto_p.h, daemon/CryptoImpl/cryptopluginwrapper.cpp, daemon/CryptoImpl/cryptopluginwrapper_p.h, daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/CryptoImpl/cryptorequestprocessor_p.h, daemon/SecretsImpl/pluginfunctionwrappers.cpp, daemon/SecretsImpl/pluginfunctionwrappers_p.h, daemon/SecretsImpl/pluginwrapper.cpp, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretscryptohelpers.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, lib/Crypto/cryptomanager.cpp, lib/Crypto/cryptomanager_p.h, lib/Crypto/storedkeyidentifiersrequest.cpp, lib/Crypto/storedkeyidentifiersrequest.h, lib/Crypto/storedkeyidentifiersrequest_p.h, plugins/inappauthplugin/plugin.cpp, plugins/sqlcipherplugin/encryptedstorageplugin.cpp, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp
If a collectionName is specified and that collection is locked,
this request will now trigger an unlock flow to retrieve the
key identifiers in the collection.
=> [sailfish-crypto] Add collectionName parameter to StoredKeyIdentifiersRequest. Contributes to JB#40058

rpm/sailfish-secrets.spec
This commit adds sailfishsecretsdaemon-secretsplugin-common that
contains plugins are mandatory for all platforms.
In addition, this commit adds four virtual packages
that are used to build proper requirement chain from upper layers.
The lower layers shall depend on the concreate packages that brings
in necessary packages satisfying upper layers.
Provides: sailfishsecretsdaemon-secretsplugins
- All secrets plugins
Provides: sailfishsecretsdaemon-secretsplugin-ssl
- Implements ssl secrets plugin e.i. openssl secrets
Provides: sailfishsecretsdaemon-secretsplugin-sql
- Implements sql secrets plugin e.i. sqlite
Provides: sailfishsecretsdaemon-cryptoplugins
- All secrets plugings
Provides: sailfishsecretsdaemon-cryptoplugin-ssl
- Implements ssl crypto plugin e.i. openssl crypto plugin
=> [sailfish-secrets] Add default plugin packages that provides plugins. Contributes to JB#40058

lib/CryptoPluginApi/extensionplugins.cpp
Some quick follow-up related to my remark in #88 updating the documentation of the plugin API.
Before accepting request (or not ;) ), one can discuss here the case when serialisation data already contains key identification data, like for PGP key objects. In that case the keyTemplate parameter of the importAndStoreKey() method is redundant. Should it be ignored? If so, I'll update the PR to add it in the documentation.
Additionally, one remark, for the importKey() method, there is no keyTemplate argument. When the serialisation data doesn't contain key names… the generated Crypto::Key will be invalid, won't it?
=> [sailfish-crypto] Update plugin documentation for changes in key importation routines.

tools/secrets-tool/commandhelper.cpp
So far we found a one-liner issue that prevents `--delete-collection` from working.
=> Fix issue discovered during testing

rpm/sailfish-secrets.spec, tests/plugins/testopensslcryptoplugin/testopensslcryptoplugin.pro
The previous PR from @rainemak missed the plugin in crypto ;)
=> [sailfish-secrets] Make opensslcrypto plugin to link with libcrypt.

daemon/controller.cpp, lib/Crypto/plugininfo.cpp, lib/Crypto/plugininfo.h, lib/Crypto/serialization.cpp, lib/Secrets/plugininfo.cpp, lib/Secrets/plugininfo.h, lib/Secrets/serialization.cpp
This PR removes the setters method from PluginInfo structure to better reflect its read-only purpose, as discussed in #90.
=> [sailfish-secrets] Make PluginInfo read-only, fixes #90.

daemon/SecretsImpl/secretsrequestprocessor.cpp
Another similar one
See also: https://github.com/sailfishos/sailfish-secrets/pull/107
=> [secrets] Change SecretsDaemonLocked error to IncorrectAuthenticationCode when unlocking master. Contributes to JB#41552

daemon/CryptoImpl/cryptopluginfunctionwrappers.cpp, daemon/CryptoImpl/cryptopluginfunctionwrappers_p.h, daemon/CryptoImpl/cryptopluginwrapper_p.h, daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/CryptoImpl/cryptorequestprocessor_p.h, daemon/SecretsImpl/pluginfunctionwrappers.cpp, daemon/SecretsImpl/pluginfunctionwrappers_p.h, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretscryptohelpers.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, lib/Crypto/key.h, tests/qml/tst_qml_signing/tst_qml_signing.qml, tools/secrets-tool/manual-test.sh
If a collection which contains a key is currently locked (due to the
unlock semantic being AccessRelock, for example), then if a client
attempts to use that key (e.g. to encrypt/decrypt/sign/verify) the
user should be prompted to unlock the collection in order to allow
the key to be retrieved in order to perform the operation.
This commit ensures that this occurs, where previously the operations
would have failed with a CollectionLocked error.
Contributes to JB#40058
=> [sailfish-crypto] Trigger collection unlock flow for crypto operations. Contributes to JB#40058

lib/Secrets/interactionrequest.cpp, lib/Secrets/result.h, plugins/passwordagentauthplugin/passwordagentplugin.cpp
If the user cancels a user input dialog, we should report this as
differently to other failures (e.g. dbus communication failure).
This commit adds a specific error code to denote this case, and
ensures that the passwordagent plugin returns that error code
from user input flows which are canceled.
=> [sailfish-secrets] Add InteractionViewUserCanceledError error code. Contributes to JB#36797

daemon/plugin_p.cpp, daemon/plugin_p.h, lib/Secrets/Plugins/extensionplugins.cpp, lib/Secrets/Plugins/extensionplugins.h, plugins/passwordagentauthplugin/passwordagentplugin.cpp, plugins/passwordagentauthplugin/passwordagentplugin.h
We build both a "normal" and a "test" version of various plugins.
Upon daemon startup, we load all plugins, and then unload any which
don't match the current mode (autotest = true/false).
This has the unfortunate side effect that the test version of the
passwordagent plugin will overwrite the socket file originally
created by the normal version of the password agent plugin, before
being unloaded.
This commit ensures that we allow plugins to perform initialization
in a specific initialize() method which is only called once the
plugin has been "accepted" for use by the daemon according to the
current mode.
=> [sailfish-secrets] Initialize passwordagent once accepted. Contributes to JB#36797

common.pri, daemon/SecretsImpl/pluginfunctionwrappers.cpp, daemon/SecretsImpl/pluginfunctionwrappers_p.h, daemon/SecretsImpl/pluginwrapper.cpp, daemon/SecretsImpl/pluginwrapper_p.h, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, lib/Secrets/collectionnamesrequest.cpp, lib/Secrets/collectionnamesrequest.h, lib/Secrets/collectionnamesrequest_p.h, lib/Secrets/secretmanager.cpp, lib/Secrets/secretmanager_p.h, tests/Secrets/tst_secretsrequests/tst_secretsrequests.cpp
This commit modifies the CollectionNamesRequest so that the lock
state of the collection is exposed, allowing the client to
modify its behaviour depending on the lock state of the collection,
rather than reacting to CollectionLocked errors.
=> [sailfish-secrets] Report collection lock state from CollectionNamesRequest. Contributes to JB#36797

tools/secrets-tool/commandhelper.cpp, tools/secrets-tool/commandhelper.h, tools/secrets-tool/main.cpp
Add support to add ```-o key=value``` options in the command line for crypto requests. This is then passed to the crypto API as customParameters. It implements #122.
=> [sailfish-secrets] Add support to pass custom parameters on CLI, fixes Github#122.

database/database.cpp, plugins/opensslcryptoplugin/evp/evp.cpp
When you run the daemon twice, the second instance cannot establish a DBus session and stop. When stopping it segfaults. It appears that some plugin objects cannot be destroied properly. There are two issues:
- plugin using database.cpp that are started but the database not created yet, should not call ```close()``` on the database object. Otherwise it segfaults in Qt. The ```isValid()``` safeguard the segfault.
- plugin using evp.cpp have an issue with the static variable s_mutexes. This static variable is created after the plugin instance and is thus destroyed before it, but the plugin destroy function calls the cleanup() function that result is a double free… see https://stackoverflow.com/questions/2204608/does-c-call-destructors-for-global-and-class-static-variables for destruction of …
=> [sailfish-secrets] Correct segfaults on exit in plugin cleanup code.

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/cryptopluginwrapper.cpp, daemon/CryptoImpl/cryptopluginwrapper_p.h, daemon/SecretsImpl/metadatadb.cpp, daemon/SecretsImpl/metadatadb_p.h, daemon/SecretsImpl/pluginwrapper.cpp, daemon/SecretsImpl/pluginwrapper_p.h, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/controller.cpp, daemon/controller_p.h, lib/Crypto/cryptomanager.cpp, lib/Secrets/secretmanager.cpp, plugins/inappauthplugin/plugin.cpp, tests/Crypto/tst_crypto/tst_crypto.cpp, tests/Crypto/tst_cryptorequests/tst_cryptorequests.cpp, tests/Crypto/tst_cryptosecrets/tst_cryptosecrets.cpp, tests/Secrets/tst_secretsrequests/tst_secretsrequests.cpp, tools/secrets-tool/commandhelper.cpp
This commit changes the client-side default plugin name variables
to be generic names (e.g. "plugin.storage.default") which then get
mapped to "real" plugin names by the daemon.
This allows the default plugins to be configurable (via .conf file
which provides environment variable values), allowing vendors to
supply their own default plugins which clients can use without
needing to modify client code.
Finally, unit tests are fixed to work with the changes.
Contributes to JB#42192
=> [sailfish-secrets] Perform plugin name mapping. Contributes to JB#42192

daemon/CryptoImpl/crypto.cpp, daemon/SecretsImpl/metadatadb.cpp, daemon/SecretsImpl/metadatadb_p.h, daemon/SecretsImpl/pluginwrapper.cpp, lib/Crypto/request.h, qml/Crypto/main.cpp, qml/Crypto/plugintypes.h
The importation request was missing from QML. This PR adds it. It also:
* correct the Request::Status type when exported to QML, to avoid error like "unsupported type Request::Status for property status of Sailfish::Crypto::ImportStoredKeyRequest";
* log reason for metadata database initialisation failures;
* add a ```constructKeyTemplate()``` method to be able to write things like that in QML:
<pre>
ImportStoredKeyRequest {
keyTemplate: cryptoManager.constructKeyTemplate(email.signingKeys[0],
"import",
"org.sailfishos.crypto.plugin.gnupg.openpgp")
}
</pre>
=> Add ImportStoredKeyRequest in QML export.

lib/Crypto/deletestoredkeyrequest.h, lib/Crypto/storedkeyrequest.h, qml/Crypto/main.cpp, qml/Crypto/plugintypes.h
The Crypto::Key::Identifier is not exposed to QML, and even not a Q_GADGET. Following the wrapper for StoredKeyIdendifierRequest, I've added wrappers for DeleteStoredKey and StoredKey requests to be able to set the identifier.
=> [sailfish-secrets] Add a helper constructIdenifier() function to be able to set it in DeleteStoredKeyRequest and StoredKeyRequest from QML.

daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, daemon/daemon.pro, lib/Secrets/Secrets.pro, lib/Secrets/healthcheckrequest.cpp, lib/Secrets/healthcheckrequest.h, lib/Secrets/healthcheckrequest_p.h, lib/Secrets/secretmanager.cpp, lib/Secrets/secretmanager.h, lib/Secrets/secretmanager_p.h, lib/Secrets/secretsdaemonconnection.cpp, lib/Secrets/serialization.cpp, lib/Secrets/serialization_p.h, qml/Secrets/main.cpp, qml/Secrets/plugintypes.h, tools/secrets-tool/commandhelper.cpp, tools/secrets-tool/main.cpp
This PR is a follow-up to the data protection PR which added the `DataProtector` class to the secrets daemon. This one deals with what happens when data corruption happens.
* Separate the cases when there is data corruption from when the data is otherwise inaccessible.
* When the data is irretrieveable, delete the data.
* When the data is irretrieveable, send a notification to the user.
Further idea:
* When just the lock code data is gone, maybe prompt the user to set up a new lock code. This is nice to have, but considering how unlikely it is that this actually happens, I have not implemented it yet. Our time is better spent elsewhere.
=> Better handling of data corruption

qml/Crypto/main.cpp, qml/Crypto/plugintypes.h
Allow to set up key generation parameters from QML bindings. One can write something like:
<pre>
keyPairGenerationParameters: cryptoManager.constructRsaKeygenParams
({"name": root.identity,
"email": root.emailAddress,
"modulusLength": 3072})
</pre>
Known parameters are set via their setters, while all other key:values are passed as custom parameters.
=> [sailfish-secrets] Add parameters to the key generation QML bindings.

qml/Crypto/main.cpp, qml/Crypto/storedkeyidentifiersrequestwrapper.cpp, qml/Crypto/storedkeyidentifiersrequestwrapper.h, qml/Secrets/findsecretsrequestwrapper.cpp, qml/Secrets/findsecretsrequestwrapper.h, qml/Secrets/main.cpp
As for #140, add wrappers for PluginInfoRequest so that the list attributes are available from QML.
@chriadam and @venemo, any remarks?
=> [sailfish-secrets] Export lists to QML from PluginInfoRequest.

daemon/CryptoImpl/cryptorequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor.cpp
There is a risk of race condition when connecting the `finished` signal after launching the thread with `setFuture()`. This is documented in the [Qt doc](http://doc.qt.io/qt-5/qfuturewatcher.html#setFuture).
I agree that the risk is quite neglectible here since the thread may have some work to do and may not return instantaneously, but it's safer by calling the setFuture() after the connection.
=> [sailfish-secrets] Call setFuture() in daemon after signal connection. Contributes to JB#36797

lib/Secrets/interactionparameters.h, plugins/gnupgplugin/gpgmebase.cpp, plugins/passwordagentauthplugin/passwordagentplugin.cpp
As discussed in #144 it is not possible at the moment to request a password creation input window without overriding the default repeat message.
This PR is fixing this by defining a new operation in InteractionParameters and detecting the creation request from operation in password plugin instead of relying on the prompt texts.
IMHO, it's more semantic to switch action depending on operation than trying to infer it from context (here prompt texts). Prompt texts should be kept for what they are: overriding default text messages in the system window.
=> [sailfish-secrets] Switch to password creation from operation(), and not from prompt texts. Contributes to JB#36797

plugins/gnupgplugin/gpgme_p.h
Email filtering is currently failing in a FindSecretRequest for S/MIME keys because emails are stored within brackets. This PR is removing the brackets if any, storing emails as they are.
@chriadam this will be necessary for selection of S/MIME keys for email signature.
=> [sailfish-secrets] Clean emails before storing them for S/MIME keys.

plugins/gnupgplugin/pinentry/qassuanserver.cpp
Passphrases can be cached as Secrets, so they are not asked everytime. Before asking to enter a passphrase to unlock a GnuPG key, the pinentry is requesting access to a Secret collection to retrieve the passhrase if stored.
This commit disables this cache retrieval if the provided passphrase was erroneous (having an error generates a prompt instruction explaining about the error).
@chriadam may you review ?
=> [sailfish-secrets] Don't fetch cache passphrase on retry. Contributes to JB#43783

rpm/sailfish-secrets.spec
Currently, pulling in the GnuPG plugin on a bare system will install the daemon but the authentication plugin that is used by pinentry is not installed.
@chriadam and @pvuorela this may solve some of the dependency issues we have went installing only this package on a bare system.
=> [sailfish-secrets] Ensure that authentication plugin are installed with GnuPG plugins.

lib/SecretsCrypto/SecretsCrypto.pro, lib/SecretsCrypto/sf-common-private.h, lib/SecretsCrypto/sf-common.c, lib/SecretsCrypto/sf-crypto-cipher-session.c, lib/SecretsCrypto/sf-crypto-cipher-session.h, lib/SecretsCrypto/sf-crypto-manager-private.h, lib/SecretsCrypto/sf-crypto-manager.c, tests/SecretsCrypto/tst_secretscrypto/tst_secretscrypto.c
This PR has two versions for update() and finish(), one that always returns a GBytes instance on success (the first commit), and in the next commit returns a boolean and uses NULL instead of empty GBytes.
I tend to like that the latter is somewhat less cumbersome, but both have their drawbacks. Comments on this welcome.
=> Add support for cipher sessions in the GObject API

plugins/passwordagentauthplugin/passwordagentplugin.cpp
Introduce a timeout attribute to interaction parameters. Use this
timeout value in password plugin to ensure that dialog is dismissed
before the request itself timeout. This avoid the request to return
an empty user input with a successful result while the dialog itself
is still being displayed.
Solve issue #155 
@chriadam there is still a possible issue with inconsistent hard coded timeout values: in `secretdaemonconnection.cpp:createInterface()` (/resp./ in crypto) the timeout is fixed to 3 minutes, which is fine for the default timeout of 2 minutes, but can create issues in my opinion if user sets up a longer timeout. The problem is that this timeout is set for the manager itself, so for all requests. I don't think it can be a good idea to change the timeout after creation when we want …
=> [sailfish-secrets] Ensure user input dialog timeout before request. Contributes to JB#44199

daemon/CryptoImpl/crypto.cpp, daemon/CryptoImpl/crypto_p.h, daemon/SecretsImpl/secrets.cpp, daemon/SecretsImpl/secrets_p.h, daemon/SecretsImpl/secretsrequestprocessor.cpp, daemon/SecretsImpl/secretsrequestprocessor_p.h, daemon/requestqueue.cpp, daemon/requestqueue_p.h, lib/Secrets/Plugins/extensionplugins.cpp, lib/Secrets/Plugins/extensionplugins.h, plugins/inappauthplugin/plugin.cpp, plugins/inappauthplugin/plugin.h, plugins/passwordagentauthplugin/passwordagentplugin.cpp, plugins/passwordagentauthplugin/passwordagentplugin.h
Closes #157 
Add listener in daemon on client DBus disconnect signal. Then notify the plugins to abort user input or authentication. Add ad hoc interface to plugins to handle cancellation.
=> [sailfish-secrets] Add a cancellation mechanism to authentication and user input requests.

lib/Crypto/cipherrequest.cpp, lib/Crypto/decryptrequest.cpp, lib/Crypto/deletestoredkeyrequest.cpp, lib/Crypto/encryptrequest.cpp, lib/Crypto/generateinitializationvectorrequest.cpp, lib/Crypto/generatekeyrequest.cpp, lib/Crypto/generaterandomdatarequest.cpp, lib/Crypto/generatestoredkeyrequest.cpp, lib/Crypto/lockcoderequest.cpp, lib/Crypto/plugininforequest.cpp, lib/Crypto/seedrandomdatageneratorrequest.cpp, lib/Crypto/signrequest.cpp, lib/Crypto/storedkeyidentifiersrequest.cpp, lib/Crypto/storedkeyrequest.cpp, lib/Crypto/verifyrequest.cpp, lib/Secrets/collectionnamesrequest.cpp, lib/Secrets/createcollectionrequest.cpp, lib/Secrets/deletecollectionrequest.cpp, lib/Secrets/deletesecretrequest.cpp, lib/Secrets/findsecretsrequest.cpp, lib/Secrets/healthcheckrequest.cpp, lib/Secrets/interactionrequest.cpp, lib/Secrets/lockcoderequest.cpp, lib/Secrets/plugininforequest.cpp, lib/Secrets/storedsecretrequest.cpp, lib/Secrets/storesecretrequest.cpp
Close #155.
The case when the DBus reply is an error was not treated previously. So, if the daemon is too slow to answer (or die?) and the CryptoManager or the SecretManager timeout, the result was successful and the result was empty.
Hopefully, I've catched all requests ;)
@chriadam or @Venemo any remarks ?
=> [sailfish-secrets] Return an error to client on DBus connection error. Fix Github#155

lib/Crypto/doc/sailfish-crypto-overview.qdoc, lib/Secrets/doc/sailfish-secrets-overview.qdoc
The Sailfish OS Secrets and Crypto Framework is still under active
development, and as such no source or binary compatibility promises
are made at this point in time.
=> [sailfish-secrets] Add disclaimer to documentation overview pages. Contributes to JB#45782

qml/Crypto/main.cpp, qml/Crypto/plugintypes.h, qml/Secrets/main.cpp, qml/Secrets/plugintypes.h
This commit undoes some of the type registration naming done in
2d1f6f80 and further improves the namespacing and type registration
to ensure that clients can use the required types unambiguously.
This change is source incompatible for clients using the types from
QML, but sailfish-secrets is not allowed for harbour currently.
=> [sailfish-secrets] Register types with appropriate meta type names. Contributes to JB#45215

plugins/gnupgplugin/pinentry/pinentry.pro, rpm/sailfish-secrets.spec
We used the wrong pkgconfig name for libgpg-error.
This changes fixes it after aligned with upstream.
=> [sailfish-secrets] Fix libgpg-error pkgconfig symbol name

daemon/controller.cpp, lib/Crypto/cryptodaemonconnection.cpp, lib/Secrets/secretsdaemonconnection.cpp, plugins/passwordagentauthplugin/passwordagentplugin.cpp
The DBus dialog is currently happening on `/run/user/100000/sailfishsecretsd-p2pSocket`. For instance when you need a confirmation to access the secret storage, or you require a password.
But for jailed application, /run is no readable. So like QMF, this MR is moving the socket to a subdirectory to allow to whitelist it.
@chriadam do you agree ?
=> [sailfish-secrets] Put the P2P DBus socket in a sub-directory of /run. Contributes to JB#56300

plugins/passwordagentauthplugin/passwordagentplugin.cpp
…ntributes to JB#56300
@chriadam , I'm confused how I could have forgotten to commit the change in socket name in the password agent too.
At the moment, `systemctl --user status lipstick-security-ui.service` is green, but actually, if you run it by hand, you notice that it warns with:
```
[W] unknown:0 - Connection to org.lipstick.securityui failed.  Failed to connect to socket /run/user/100000/sailfishsecretsd/p2pSocket-agent: Aucun fichier ou dossier de ce type
```
As a consequence, there is no system prompt for password or anything related to password entry. Any attempt is failing with:
```
[D] unknown:0 - Starting passphrase request
[D] unknown:0 - -> return code Sailfish::Secrets::Result::ResultCode(Failed)
[W] unknown:0 - "No password agent is registered"
```
I was sure I did the …
=> [sailfish-secrets] Correct p2p socket name for the password agent. Contributes to JB#56300

plugins/passwordagentauthplugin/passwordagentplugin.cpp
Plugin are initialised before the daemon is creating its own
socket and ensuring the exitence of the directory under
/run/user/xxx/sailfishsecretsd. So create also that directory
in the password agent plugin which is using this directory.
@chriadam : this is the true root of the problem, I guess. By moving the socket under a subdirectory, I created an issue with this plugin that was then unable to start its QDBusServer because the path was not existing yet (it's created later on by the daemon). It also explains why when testing it was always working : because then the directory was existing and everything was working after a daemon restart. While it was not working directly after a boot of the device.
=> [sailfish-secrets] Create the socket directory in the plugin also. Contributes to JB#56300

daemon/SecretsImpl/metadatadb.cpp
@chriadam and @pvuorela this is a minimal change to allow to use SQLCipher 4 with our database without handling a migration.
This is not optimal, but at least one can update SQLCipher without too much fuss. It's still possible to later migrate the databases to version 4 in another PR. See sailfishos/sqlcipher#4
=> [sailfish-secrets] Indicate that SQLCipher db version is 3.

plugins/gnupgplugin/pinentry/qassuanserver.cpp
Also don't bother the user with a second demand to access the cache passphrase if the first attempt was dismissed.
@pvuorela , if you have time to give a look. Thank you.
=> [sailfish-secrets] Properly detect the key ID in case of a subkey.

lib/Crypto/keypairgenerationparameters.cpp, lib/Crypto/keypairgenerationparameters.h
Newer compilers warn about implicitly declared copy-contstructors. Here there were almost proper explicitly defined ones but they take the parent class parameter. Such a code is also needed as KeyPairGenerationParameters::isValid() tries to create copies with parent class reference.
=> [sailfish-secrets] Declare proper copy constructors for KeyPairGenerationParameters. JB#55609
